swagger: '2.0'
info:
  title: API de usuarios
  description: API para el manejo de usuarios
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: usuarios
    description: Endpoints para usuarios
paths:
  /users/logout:
    post:
      tags:
        - usuarios
      summary: Cierre de sesión de usuario
      description: Cerrar la sesión de un usuario autenticado
      security:
        - BearerAuth: []
      responses:
        200:
          description: Sesión cerrada correctamente
        401:
          description: No se encontró un token válido en la petición
        500:
          description: Error del servidor
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
